AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for bswdegree.org website infrastructure'

Resources:
  # S3 bucket for website hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bswdegree.org
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # Bucket policy to allow only CloudFront to access the S3 bucket
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: 'PolicyForCloudFrontPrivateContent'
        Statement:
          - Sid: 'AllowCloudFrontServicePrincipal'
            Effect: 'Allow'
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket, '/*']]
            Condition:
              ArnLike:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::795714918442:distribution/${WebsiteDistribution}'

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for bswdegree.org
        
  # CloudFront distribution - will be imported
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: WebsiteBucket
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution for bswdegree.org
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        # If you have custom domain and SSL certificate, uncomment and configure
        # Aliases:
        #   - bswdegree.org
        #   - www.bswdegree.org
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref CertificateArn
        #   SslSupportMethod: sni-only
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 0
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  WebsiteBucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref WebsiteBucket

  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref WebsiteDistribution
    
  CloudFrontDomain:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt WebsiteDistribution.DomainName
