AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for bswdegree.org website infrastructure'

Resources:
  # S3 bucket for website hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: bswdegree.org
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # Origin Access Control for CloudFront to access S3
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: 'Origin Access Control for bswdegree.org S3 bucket'

  # Bucket policy to allow CloudFront access via OAC
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: 'PolicyForCloudFrontPrivateContent'
        Statement:
          - Sid: 'AllowCloudFrontServicePrincipal'
            Effect: 'Allow'
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Action: 's3:GetObject'
            Resource: 'arn:aws:s3:::bswdegree.org/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': 'arn:aws:cloudfront::795714918442:distribution/E1DPKTG96SLOP7'

  # CloudFront function for URL rewriting to add index.html - using existing function
        
  # CloudFront distribution - will be imported
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: WebsiteBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution for bswdegree.org
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        Aliases:
          - bswdegree.org
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:795714918442:certificate/2b33fab8-39d6-4ea1-867d-64ea8085b35d
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        DefaultRootObject: index.html
        CustomErrorResponses:
          # Handle 403 Access Denied errors (when object doesn't exist)
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          # Handle 404 Not Found errors
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 0
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: 'arn:aws:cloudfront::795714918442:function/BswDegreeOrg-index-rewrite'


Outputs:
  WebsiteBucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref WebsiteBucket

  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref WebsiteDistribution
    
  CloudFrontDomain:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt WebsiteDistribution.DomainName
